const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const LOG_OUT = 'LOG_OUT';
const ERROR = 'ERROR';
const CLEAR_ERROR= 'CLEAR_ERROR'
const LOADING_TRUE = 'LOADING_TRUE';
const LOADING_FALSE = 'LOADING_FALSE';
const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
const CLEAR_FOLLOW_STATUS = 'CLEAR_FOLLOW_STATUS';
const SEARCH_USER = 'SEARCH_USER';
const GET_TIMELINE = 'GET_TIMELINE';
const GET_MYCLASSES= 'GET_MYCLASSES';

export {SIGN_IN,SIGN_UP,LOG_OUT,ERROR,LOADING_FALSE,LOADING_TRUE,CLEAR_SEARCH_RESULTS,SEARCH_USER,GET_TIMELINE,GET_MYCLASSES,CLEAR_ERROR, CLEAR_FOLLOW_STATUS};